"""The report's figures (US-126, spec section 6.3).

Only one figure is load-bearing: campaign recall as a function of the daily
alert budget, one curve per model. It is the visual form of the project's
whole question — at a budget an analyst could actually work, how much of the
published deep-learning advantage over well-built heuristics survives?

Figures are pipeline *output*: regenerated by `authbench demo` and by the
DVC `train_eval` stage, never hand-edited (`.gitignore` keeps
`reports/figures/` out of git for exactly that reason).
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

# A report figure is written on CI runners and in DVC stages with no display
# attached; select the non-interactive backend before pyplot is imported.
matplotlib.use("Agg")

import matplotlib.pyplot as plt  # noqa: E402

from authbench.evaluate.budget import BudgetCurve  # noqa: E402

CAMPAIGN_RECALL_FIGURE = "campaign_recall_vs_budget.png"

# The floors (M0) are reference lines, not competitors: a random scorer and an
# always-fail scorer exist to show what a given recall is worth. Drawing them
# in the same visual register as the real models is how a reader mistakes
# "beats the floor" for "is good".
_FLOOR_PREFIX = "M0"


def _is_floor(model_name: str) -> bool:
    return model_name.startswith(_FLOOR_PREFIX)


def plot_campaign_recall_vs_budget(
    curves: list[BudgetCurve],
    out_path: Path,
    *,
    title: str = "Campaign recall vs. daily alert budget",
    subtitle: str | None = None,
    dpi: int = 200,
) -> Path:
    """Write the headline figure to `out_path` and return it.

    `curves` is what `compute_budget_curve` produces, one per model. The x
    axis is logarithmic because the budgets sweep an order of magnitude
    (10 -> 500) and a linear axis would crush the low-budget end — which is
    the operationally interesting one.
    """
    if not curves:
        raise ValueError("plot_campaign_recall_vs_budget needs at least one BudgetCurve.")

    out_path.parent.mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(figsize=(7.5, 4.8))

    models = [c for c in curves if not _is_floor(c.model_name)]
    floors = [c for c in curves if _is_floor(c.model_name)]

    colors = plt.get_cmap("tab10")
    # Campaign recall is a ratio over a small integer count of campaigns, so
    # models genuinely tie all the time (every curve at 100% on a test split
    # with one campaign). Distinct markers plus transparency keep a tied curve
    # visible underneath the one drawn last, instead of silently erasing it.
    markers = ["o", "s", "^", "D", "v", "P", "*", "X"]
    for idx, curve in enumerate(models):
        ax.plot(
            curve.budgets,
            [r * 100 for r in curve.campaign_recall],
            marker=markers[idx % len(markers)],
            markersize=6,
            linewidth=1.9,
            alpha=0.75,
            color=colors(idx % 10),
            label=curve.model_name,
        )

    for curve in floors:
        ax.plot(
            curve.budgets,
            [r * 100 for r in curve.campaign_recall],
            linestyle="--",
            linewidth=1.3,
            color="0.55",
            marker="x",
            markersize=5,
            label=f"{curve.model_name} (floor)",
        )

    ax.set_xscale("log")
    ax.set_xticks(curves[0].budgets)
    ax.set_xticklabels([str(b) for b in curves[0].budgets])
    ax.set_xlabel("Daily alert budget (alerts / day)")
    ax.set_ylabel("Campaign recall (%)")
    ax.set_ylim(-3, 103)
    ax.grid(True, which="major", linestyle=":", linewidth=0.6, alpha=0.7)
    ax.set_axisbelow(True)

    ax.set_title(title, fontsize=12, pad=22 if subtitle else 8)
    if subtitle:
        # Sits in the gap opened by the title's pad — above the axes, below
        # the title — so it never lands on top of either.
        ax.text(
            0.0,
            1.015,
            subtitle,
            transform=ax.transAxes,
            fontsize=8.5,
            color="0.35",
            va="bottom",
        )

    ax.legend(loc="lower right", fontsize=8.5, framealpha=0.9)
    fig.tight_layout()
    fig.savefig(out_path, dpi=dpi)
    plt.close(fig)

    return out_path
